## https://en.wikipedia.org/wiki/YAML
--- # Favorite movies
- Casablanca
- North by Northwest
- The Man Who Wasn't There

--- # Shopping list
- [milk, pumpkin pie, eggs, juice]
#
--- # Indented Block
- name: John Smith
  age: 33
##--- # Inline Block
- {name: John Smith, age: 33}
#
--- # multi line str
- data: |
   There once was a short man from Ealing
   Who got on a bus to Darjeeling
       It said on the door
       "Please don't spit on the floor"
   So he carefully spat on the ceiling

--- # multi line str
- data2: >
   Wrapped text
   will be folded
   into a single
   paragraph

   Blank lines denote
   paragraph breaks

- {name: John Smith, age: 33}
- name: Mary Smith
  age: 27

- men: [John Smith, Bill Jones]
- women:
  - Mary Smith
  - Susan Williams
#
#
## advanced
# sequencer protocols for Laser eye surgery
---
- step:  &id001                  # defines anchor label &id001
    instrument:      Lasik 2000
    pulseEnergy:     5.4
    pulseDuration:   12
    repetition:      1000
    spotSize:        1mm

- step: &id002
    instrument:      Lasik 2000
    pulseEnergy:     5.0
    pulseDuration:   10
    repetition:      500
    spotSize:        2mm
- step: *id001                   # refers to the first step (with anchor &id001)
- step: *id002                   # refers to the second step
- step:
    <<: *id001
    spotSize: 2mm                # redefines just this key, refers rest from &id001
- step: *id002
